sonar.projectKey=colife-front
sonar.projectName=CoLife Frontend
sonar.sources=src
sonar.exclusions=src/test/**,**/*.test.ts,**/*.test.tsx,node_modules/**,coverage/**,dist/**
sonar.coverage.exclusions=\
  src/pages/WelcomePage.tsx,\
  src/pages/admin/AdminProfilePage.tsx,\
  src/components/admin/AdminLayout.tsx,\
  src/components/admin/AdminTopBar.tsx,\
  src/components/admin/AdminSidebar.tsx,\
  src/components/admin/QuickActions.tsx,\
  src/components/admin/UpcomingActivitiesTable.tsx,\
  src/components/admin/AdminActivityDetailModal.tsx,\
  src/components/home/**,\
  src/components/layout/**,\
  src/components/AdminRoute.tsx,\
  src/components/ProtectedRoute.tsx,\
  src/components/CreateActivityModal.tsx,\
  src/components/EditActivityModal.tsx,\
  src/components/activity/ActivityTypeSelect.tsx,\
  src/components/ui/PasswordStrengthIndicator.tsx,\
  src/context/**,\
  src/layout/**,\
  src/auth/**,\
  src/types/**,\
  src/App.tsx,\
  src/main.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
